<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.goalias</groupId>
        <artifactId>os-service</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>service-chat</artifactId>

    <properties>
        <dashscope.version>1.7.1-beta14</dashscope.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.goalias</groupId>
            <artifactId>common-chat</artifactId>
        </dependency>

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-community-dashscope</artifactId>
            <version>${dashscope.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-model-openai</artifactId>
        </dependency>
    </dependencies>

</project>